[profile.default]
src = "src"
out = "../abi"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./.env" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
